### ISSUE TITLE
Command name consistancy

### ISSUE THREAD

**Issue by codesections** [masukomi/hey_3#31]
`hey kill timer <id>` and `hey summarize timers`  use multi-word commands, but `hey log-interrupts` uses a hyphen.  It seems like hey should pick one style and stick to it.

(This is very minor, but it's easier to change now).

I don't have strong feelings on which style to adopt, but I mildly prefer the hyphenated version (which IME is more common).

**Comment by masukomi** [comment]
`hey log-interrupts` replaced with `hey log interrupts` in e056919b19f0f1182f75cfe82875acd9cba1c49d (in the beta_10 branch).

I agree it's less standard but I'm going for a more human language interface because i find interfacing with cli apps way easier when they don't require remembering a bunch of magical incantations and can just use simple english (or something close to it) . ;)
